# Generated by Django 5.2.1 on 2025-06-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hearthub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="waterintake",
            name="fluidrestriction",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
