# Generated by Django 5.2.1 on 2025-06-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hearthub", "0002_waterintake_fluidrestriction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterintake",
            name="amount",
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="waterintake",
            name="fluidrestriction",
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5),
        ),
    ]
