# Generated by Django 5.2.1 on 2025-06-21 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hearthub", "0003_alter_waterintake_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterintake",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drinker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
