# Generated by Django 5.2.1 on 2025-06-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hearthub", "0004_alter_waterintake_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterintake",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
