# Generated by Django 5.2.1 on 2025-06-21 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hearthub", "0005_alter_waterintake_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterintake",
            name="fluidrestriction",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=2000, max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="waterintake",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="water_intakes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
