# Generated by Django 5.2.1 on 2025-06-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hearthub", "0006_alter_waterintake_fluidrestriction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterintake",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="waterintake",
            name="fluidrestriction",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=2000, max_digits=5, null=True
            ),
        ),
    ]
