# Generated by Django 5.2.1 on 2025-06-24 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hearthub", "0007_alter_waterintake_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterintake",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
