# Generated by Django 5.2.3 on 2025-06-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hearthub", "0009_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="weight",
            name="weight_change",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="weight",
            name="IBW",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=80, max_digits=4, null=True
            ),
        ),
    ]
