# Generated by Django 5.2.3 on 2025-06-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hearthub", "0010_weight_weight_change_alter_weight_ibw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weight",
            name="weight_change",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
