# Generated by Django 5.2.3 on 2025-06-30 03:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hearthub", "0011_alter_weight_weight_change"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Symptoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "breathlessness",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                (
                    "cough",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                (
                    "leg_swelling",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                (
                    "abdomen_swelling",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                (
                    "sleeping",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                (
                    "other",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptoms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
