# Generated by Django 5.2.3 on 2025-06-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hearthub", "0012_symptoms"),
    ]

    operations = [
        migrations.AddField(
            model_name="symptoms",
            name="symptom_alert",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="weight",
            name="weight_change",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
